### ISSUE TITLE
[BUG] Null pointer ref on FirstAudioStream() in checkFile()

### ISSUE THREAD

**Issue by sjthespian** [aetaric/checkrr#108]
**Describe the bug**
I just had a SEGV while running my initial scan of my music library. From the logs, it looks like it was in the middle of an album, as far as I can tell there is nothing wrong with the file it was probably scanning at the time.

docker log output:
```
checkrr  | panic: runtime error: invalid memory address or nil pointer dereference
checkrr  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x85a263]
checkrr  |
checkrr  | goroutine 1 [running]:
checkrr  | github.com/aetaric/checkrr/check.(*Checkrr).checkFile(0xc00062e700, {0xc0007741e0, 0x4c})
checkrr  | 	/Users/aetaric/src/checkrr/check/checkrr.go:288 +0xd43
checkrr  | github.com/aetaric/checkrr/check.(*Checkrr).Run.func1({0xc0007741e0, 0x4c}, {0x10aace8?, 0xc00086d6c0?}, {0x0?, 0x0?})
checkrr  | 	/Users/aetaric/src/checkrr/check/checkrr.go:143 +0x839
checkrr  | path/filepath.walkDir({0xc0007741e0, 0x4c}, {0x10aace8, 0xc00086d6c0}, 0xc00001acc8)
checkrr  | 	/opt/homebrew/Cellar/go/1.21.3/libexec/src/path/filepath/path.go:457 +0x50
checkrr  | path/filepath.walkDir({0xc00046e980, 0x3c}, {0x10aace8, 0xc00061ab80}, 0xc00001acc8)
checkrr  | 	/opt/homebrew/Cellar/go/1.21.3/libexec/src/path/filepath/path.go:479 +0x287
checkrr  | path/filepath.walkDir({0xc000a582e8, 0x12}, {0x10aace8, 0xc00027de00}, 0xc00001acc8)
checkrr  | 	/opt/homebrew/Cellar/go/1.21.3/libexec/src/path/filepath/path.go:479 +0x287
checkrr  | path/filepath.walkDir({0xc000278760, 0x7}, {0x10aaee0, 0xc000a087b0}, 0xc00001acc8)
checkrr  | 	/opt/homebrew/Cellar/go/1.21.3/libexec/src/path/filepath/path.go:479 +0x287
checkrr  | path/filepath.WalkDir({0xc000278760, 0x7}, 0xc0000c0cc8)
checkrr  | 	/opt/homebrew/Cellar/go/1.21.3/libexec/src/path/filepath/path.go:547 +0xaf
checkrr  | github.com/aetaric/checkrr/check.(*Checkrr).Run(0xc00062e700)
checkrr  | 	/Users/aetaric/src/checkrr/check/checkrr.go:94 +0x7c5
checkrr  | main.main()
checkrr  | 	/Users/aetaric/src/checkrr/main.go:155 +0xc05
checkrr exited with code 2
```

The last few lines of checkrr.log (this album has 33 tracks):
```
time="2024-10-07T18:46:01-07:00" level=info msg="/music/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/10 Sunny Harmony.mp3" FFProbe=true Format="MP2/3 (MPEG audio layer 2/3)" Type=Audio
time="2024-10-07T18:46:01-07:00" level=info msg="/music/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/11 Unrest.mp3" FFProbe=true Format="MP2/3 (MPEG audio layer 2/3)" Type=Audio
time="2024-10-07T18:46:01-07:00" level=info msg="/music/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/12 Infiltration.mp3" FFProbe=true Format="MP2/3 (MPEG audio layer 2/3)" Type=Audio
time="2024-10-07T18:46:01-07:00" level=info msg="/music/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/13 Maneuvering.mp3" FFProbe=true Format="MP2/3 (MPEG audio layer 2/3)" Type=Audio
time="2024-10-07T18:46:01-07:00" level=info msg="/music/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/14 Lockdown.mp3" FFProbe=true Format="raw MPEG-4 video" Type=Audio
```

**To Reproduce**
Unknown, I am just now restarting checkrr to see if it crashes in the same place. It took several hours to get to the point where it crashed.

**Expected behavior**
The app shouldn't throw a SEGV. :-)

**Desktop (please complete the following information):**
 - OS: MacOS, Docker under Ubuntu 22.04
 - Browser: N/A
 - checkrr 3.3.0

**Additional context**
If it crashes at the same point, I'll add the file I believe was being scanned as an attachment.

At least from my Mac, these files app appear to have valid mp3 magic numbers:
```
/media/mp3/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/13 Maneuvering.mp3:                     Audio file with ID3 version 2.3.0
/media/mp3/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/14 Lockdown.mp3:                        Audio file with ID3 version 2.3.0
/media/mp3/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/15 Invasion.mp3:                        Audio file with ID3 version 2.3.0
/media/mp3/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/16 Destiny.mp3:                         Audio file with ID3 version 2.3.0
/media/mp3/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/17 Parting.mp3:                         Audio file with ID3 version 2.3.0
```

**Comment by aetaric** [comment]
Hmm, line 288 in check/checkrr.go is `log.Debug(data.FirstAudioStream().CodecName)` which implies that ffprobe wasn't able to read the first audio stream's codec name. I'd be curious to know what ffprobe outputs for the file that it seg faulted on. 

There definitely needs to be a null check here on `FirstAudioStream()` before calling `CodecName` and should probably surface a bad file event if it's an audio file and the audio stream is null.

**Comment by sjthespian** [comment]
It does look like there is something funky with that file... It failed in the same place. Here's the ffprobe output:

```
❯ docker exec -ti checkrr /bin/sh
/ # ffprobe "/music/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/14 Lockdown.mp3"
ffprobe version 6.1.1 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13.2.1 (Alpine 13.2.1_git20231014) 20231014
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto=auto --enable-lv2 --enable-openssl --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   5.  0.100 /  5.  0.100
  libpostproc    57.  3.100 / 57.  3.100
[m4v @ 0x7f4ef3ead600] Format m4v detected only with low score of 5, misdetection possible!
[mpeg4 @ 0x7f4ef3ccfb00] time_increment_bits 0 is invalid in relation to the current bitstream, this is likely caused by a missing VOL header
[mpeg4 @ 0x7f4ef3ccfb00] time_increment_bits set to 16 bits, based on bitstream analysis
[mpeg4 @ 0x7f4ef3ccfb00] time_increment_bits 4 is invalid in relation to the current bitstream, this is likely caused by a missing VOL header
[mpeg4 @ 0x7f4ef3ccfb00] time_increment_bits set to 5 bits, based on bitstream analysis
[mpeg4 @ 0x7f4ef3ccfb00] time_increment_bits 5 is invalid in relation to the current bitstream, this is likely caused by a missing VOL header
[mpeg4 @ 0x7f4ef3ccfb00] time_increment_bits set to 16 bits, based on bitstream analysis
[mpeg4 @ 0x7f4ef3ccfb00] looks like this file was encoded with (divx4/(old)xvid/opendivx) -> forcing low_delay flag
[mpeg4 @ 0x7f4ef3ccfb00] low_delay flag set incorrectly, clearing it
Input #0, m4v, from '/music/Soundtracks/Fullmetal Alchemist Original Soundtrack 1/14 Lockdown.mp3':
  Metadata:
    title           : Lockdown
    artist          : Michiru Oshima
    track           : 14/33
    album           : Fullmetal Alchemist Original Soundtrack 1
    disc            : 1/1
    genre           : Soundtrack
    TMED            : CD
    MusicBrainz Release Group Id: 0d0869a0-b725-35bc-9fc5-915fdfbc180c
    TORY            : 2004
    MusicBrainz Release Track Id: 504472cc-19c2-3e11-aeae-252ece0c9e45
    SCRIPT          : Latn
    album_artist    : Michiru Oshima
    TSO2            : Oshima, Michiru
    artist-sort     : Oshima, Michiru
    ASIN            : B000BV7XYE
    originalyear    : 2004
    ARTISTS         : Michiru Oshima
    MusicBrainz Album Release Country: JP
    album-sort      : Full Metal Alchemist Original Soundtrack
    MusicBrainz Album Status: pseudo-release
    MusicBrainz Album Type: album/soundtrack
    MusicBrainz Album Id: 6a912f9a-93f7-45a9-ac9c-32bcb38ae41f
    MusicBrainz Artist Id: e6fae4d5-2a94-433d-b046-e34d7d136429
    MusicBrainz Album Artist Id: e6fae4d5-2a94-433d-b046-e34d7d136429
    date            : 2005-10-26
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: mpeg4 (Simple Profile), yuv420p, 768x576 [SAR 1:1 DAR 4:3], 25 fps, 23.98 tbr, 1200k tbn
```

I just tried playing it as well, and it fails to play. Time to pull that one back from my backups, unless it's been corrupted all along.

**Comment by aetaric** [comment]
I'll have this patched in 3.4.0.

**Comment by sjthespian** [comment]
FYI, I don't want to open another issue about this unless you want one, but it looks like when checkrr crashes and I restart it it leaves the "Run Now" button disabled in the web UI and thinks it is still running. I assume this is something in the DB, is there a way to reset it? I've been doing a single run by specifying `command: "-o"` in my docker-compose and disabling restart to get around it for testing.

I'm hoping it will restart the scan automatically at midnight, but not sure since it says "Running" in the web UI.

Or if you prefer I can open an issue so you have a way to track it.

**Comment by aetaric** [comment]
Yeah, this is a known issue, it was discussed in #91. I'll just reopen that one.

**Comment by sjthespian** [comment]
Thanks! I need to dig into that API a bit more... I'm sure there are other goodies in there. :-)
