### ISSUE TITLE
Can't start container since 3.1.0

### ISSUE THREAD

**Issue by KnifeFed** [aetaric/checkrr#44]
Unraid 6.11.5

```log
2023-01-22T15:36:29.912062710Z [32m[0m
2023-01-22T15:36:29.912101863Z [32m            _|                               _|[0m
2023-01-22T15:36:29.912112023Z [32m   _|_|_|   _|_|_|       _|_|       _|_|_|   _|  _|     _|  _|_|   _|  _|_|[0m
2023-01-22T15:36:29.912118425Z [32m _|         _|    _|   _|_|_|_|   _|         _|_|       _|_|       _|_|[0m
2023-01-22T15:36:29.912123574Z [32m _|         _|    _|   _|         _|         _|  _|     _|         _|[0m
2023-01-22T15:36:29.912128423Z [32m   _|_|_|   _|    _|     _|_|_|     _|_|_|   _|    _|   _|         _|[0m
2023-01-22T15:36:29.912133272Z Checkrr version 3.1.0
2023-01-22T15:36:29.912137941Z  Commit: 07fce6dc21047d27d3556ecce687df174b968c7a
2023-01-22T15:36:29.912142780Z  Built On: 2023-01-22T03:46:21Z
2023-01-22T15:36:29.912147459Z  Built By: goreleaser
2023-01-22T15:36:29.912393992Z time="2023-01-22T15:36:29Z" level=info msg="Using config file: /etc/checkrr.yaml"
2023-01-22T15:36:29.920840185Z panic: runtime error: invalid memory address or nil pointer dereference
2023-01-22T15:36:29.920849633Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x160 pc=0x840f38]
2023-01-22T15:36:29.920853190Z 
2023-01-22T15:36:29.920856396Z goroutine 1 [running]:
2023-01-22T15:36:29.920859532Z github.com/spf13/viper.(*Viper).AllKeys(0x0)
2023-01-22T15:36:29.920862748Z 	/Users/aetaric/go/pkg/mod/github.com/spf13/viper@v1.15.0/viper.go:1969 +0x98
2023-01-22T15:36:29.920876233Z github.com/aetaric/checkrr/check.(*Checkrr).connectServices(0xc000164000)
2023-01-22T15:36:29.920903524Z 	/Users/aetaric/src/checkrr/check/checkrr.go:182 +0x91
2023-01-22T15:36:29.920911980Z github.com/aetaric/checkrr/check.(*Checkrr).Run(0xc000164000)
2023-01-22T15:36:29.920920466Z 	/Users/aetaric/src/checkrr/check/checkrr.go:61 +0x1f2
2023-01-22T15:36:29.920929042Z main.main()
2023-01-22T15:36:29.920936667Z 	/Users/aetaric/src/checkrr/main.go:155 +0xc32
```

**Comment by aetaric** [comment]
@KnifeFed What's your config look like?

**Comment by KnifeFed** [comment]
```yaml
checkrr:
  checkpath:
    - /media/movies/lib
    - /media/tv/lib
    - /media/s01e01/lib
    - /media/mma/lib
  database: ./checkrr.db
  removeunknownfiles: false
  debug: false
  csvfile: './badfiles.csv'
  logfile: './checkrr.log'
  logjson: false
  cron: '@daily'
  ignorehidden: true
  ignoreexts:
    - .txt
    - .nfo
    - .nzb
    - .url
    - .ass
    - .srt
    - .sub
    - .idx
webserver:
  port: 8585
  baseurl: '/'
  trustedproxies:
    - 127.0.0.1
```

**Comment by aetaric** [comment]
@KnifeFed Going to push 3.1.1 to resolve this.

**Comment by KnifeFed** [comment]
Awesome!
